name: Building recovery

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  watch:
    types: [started]

env:
  MANIFEST: git://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-10.0
  DEVICE: phoenix
  DT_LINK: https://github.com/hraj9258/android_device_xiaomi_phoenix
  DT_PATH: device/xiaomi/phoenix
  TARGET: recoveryimage
  TZ: Asia/Kolkata

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
         
       - name: Initializing environment
         run: |
            sudo apt install aria2 
            sudo apt install ffmpeg 
            wget https://versaweb.dl.sourceforge.net/project/crdroid/phoenix/8.x/crDroidAndroid-12.1-20220517-phoenix-v8.5.zip
            ffmpeg -i output.mkv -vcodec libx265 -crf 28 t.mkv
            curl -sL https://git.io/file-transfer | sh 
            ./transfer wet crDroidAndroid-12.1-20220517-phoenix-v8.5.zip
